clean-up
update run_tests workflow

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,45 +1,46 @@
-name: Playwright Tests
+name: Run Playwright Tests
 on:
-  # push:
-  #   branches: [ main ]
   workflow_dispatch:
-  pull_request:
-    branches: [ main ]
+  push:
+    branches: 
+        - main
+
 jobs:
   run_playwright_tests:
     runs-on: ubuntu-20.04
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 20
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
 
-    - name: Install dependencies
-      run: npm ci   
+      - name: Install dependencies
+        run: npm ci   
 
-    - name: Install Playwright Browsers
-      run: npx playwright install --with-deps
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
 
-    - name: Run Playwright tests
-      env:
-        DEBUG: playwright:*
-      run: npx playwright test
-      continue-on-error: true
+      - name: Run Playwright tests
+        id: run_tests
+        env:
+          DEBUG: playwright:*
+        run: npx playwright test
+        continue-on-error: true
 
-    - name: playwright test artifacts
-      uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
-      with:
-        name: playwright_html_report
-        path: '**/html-report/**/*'
-        retention-days: 2
-    
-    - name: Check failure status and mark job as failed
-      if: failure()  # This step runs only if any previous step failed
-      run: |
-        echo "One of the steps failed!"
-        exit 1
+      - name: playwright test artifacts
+        uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright_html_report
+          path: '**/html-report/**/*'
+          retention-days: 2
+      
+      - name: Check failure status of tests and mark job as failed
+        if: ${{ steps.run_tests.outcome == 'failure' }} 
+        run: |
+          echo "Some tests have failed!"
+          exit 1
